###
# Application manager deployment
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: application-manager
  name: application-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: application-manager
  template:
    metadata:
      labels:
        cluster: management
        component: application-manager
    spec:
      containers:
        - name: application-manager
          image: __NPH_REGISTRY_NAMESPACE/application-manager:__NPH_VERSION
          imagePullPolicy: Always
          args:
            - "run"
            - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
            - "--conductorAddress=conductor.__NPH_NAMESPACE:5000"
            - "--queueAddress=broker.__NPH_NAMESPACE:6650"
          securityContext:
            runAsUser: 2000
