###
# Application manager deployment
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: application-manager
  name: application-manager
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: application-manager
  template:
    metadata:
      labels:
        cluster: management
        component: application-manager
    spec:
      containers:
      - name: application-manager
        image: nalejregistry.azurecr.io/nalej/application-manager:VERSION
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.nalej:8800"
        - "--conductorAddress=conductor.nalej:5000"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
