[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name="github.com/onsi/ginkgo"
    version="v1.7.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.3"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="github.com/nalej/derrors"
    version="=v2.1.0"

[[constraint]]
    name="github.com/nalej/grpc-application-go"
    version="=v0.0.92"

[[constraint]]
    name="github.com/nalej/grpc-application-manager-go"
    version="=v0.0.49"

[[constraint]]
    name="github.com/nalej/grpc-application-history-logs-go"
    version="=v0.0.1"

[[constraint]]
    name="github.com/nalej/grpc-application-network-go"
    version="=v0.0.15"

[[constraint]]
    name="github.com/nalej/grpc-conductor-go"
    version="=v0.0.96"

[[constraint]]
    name="github.com/nalej/grpc-device-go"
    version="=v0.0.33"

[[constraint]]
    name="github.com/nalej/grpc-organization-go"
    version="=v0.0.34"

[[constraint]]
    name="github.com/nalej/grpc-organization-manager-go"
    version="=v0.0.3"

[[constraint]]
    name="github.com/nalej/grpc-common-go"
    version="=v0.0.34"

[[constraint]]
    name="github.com/nalej/grpc-infrastructure-go"
    version="=v0.0.38"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "=v1.1.4"

[[constraint]]
  name = "github.com/tidwall/sjson"
  version = "=v1.0.4"

[[constraint]]
  name = "github.com/nalej/nalej-bus"
#  version ="=v0.4.0"
  branch = "master"

[[constraint]]
  name = "github.com/nalej/grpc-unified-logging-go"
  version = "v0.0.12"

[[constraint]]
    name="github.com/hashicorp/golang-lru"
    version="v0.5.0"